#pragma kernel Kernel2n64
#pragma kernel Kernel2n32
#pragma kernel Kernel2n16
#pragma kernel Kernel2n8
#pragma kernel Kernel2n4
#pragma kernel Kernel2n2
#pragma kernel Kernel2n1

#pragma kernel OctreeLeafsKernel64
#pragma kernel OctreeLeafsKernel32
#pragma kernel OctreeLeafsKernel16
#pragma kernel OctreeLeafsKernel8
#pragma kernel OctreeLeafsKernel4
#pragma kernel OctreeLeafsKernel2
#pragma kernel OctreeLeafsKernel1

#pragma kernel OctreeNeighborsKernel64
#pragma kernel OctreeNeighborsKernel32
#pragma kernel OctreeNeighborsKernel16
#pragma kernel OctreeNeighborsKernel8
#pragma kernel OctreeNeighborsKernel4
#pragma kernel OctreeNeighborsKernel2
#pragma kernel OctreeNeighborsKernel1

RWStructuredBuffer<float3> Position;
RWStructuredBuffer<float3> Direction;
RWStructuredBuffer<float> PerceptionRadius;
RWStructuredBuffer<float> HorizontalFOV;
RWStructuredBuffer<float> VerticalFOV;

Texture3D<half4> Octree;

RWTexture2D<half4> TreeLeafs;
RWTexture2D<half4> TreeNeighbors;

float xmin;
float xmax;
float ymin;
float ymax;
float zmin;
float zmax;

uint agentsCount;
uint neighborhoodCount;
uint axis;
uint treeDepth;
uint treeLeafsCount;

RWStructuredBuffer<int> Neighborhood;


void Kernel2n (uint3 id) {

    float3 pos = Position[id.x];
    float3 dir = Direction[id.x];
    float radii = PerceptionRadius[id.x];
    float hFOV = HorizontalFOV[id.x];
    float vFOV = VerticalFOV[id.x];

    float3 x = normalize(dir);
    float3 z = normalize(cross(x, float3(0, 1, 0)));
    float3 y = normalize(cross(z, x));

    for (uint i = 0; i < agentsCount; i++) {
        TreeNeighbors[uint2(id.x, i)] = half4(0, 0, 0, 0);

        float3 npos = Position[i];

        if (distance(pos, npos) <= radii) {

            float3 v = npos - pos;

            float3 p = float3(
                x.x * v.x + x.y * v.y + x.z * v.z,
                y.x * v.x + y.y * v.y + y.z * v.z,
                z.x * v.x + z.y * v.y + z.z * v.z
            );

            float a_y = degrees(atan2(p.z, p.x));
            a_y *= -1;

            float a_z = degrees(atan2(p.y, p.x));

            if (abs(a_y) <= hFOV / 2 && abs(a_z) <= vFOV / 2) {
                TreeNeighbors[uint2(id.x, i)] = half4(1, 0, 0, 0);
            }
        }
    }

    for (uint k = 0; k < neighborhoodCount; k++) {
        Neighborhood[id.x * neighborhoodCount + k] = -1;
    }

    uint ni = 0;
    uint ai = 0;

    while (ai < agentsCount && ni < neighborhoodCount) {
        if (TreeNeighbors[uint2(id.x, ai)].x > 0 && ai != id.x) {
            Neighborhood[id.x * neighborhoodCount + ni] = ai;
            ni++;
        }
        ai++;
    }
}

[numthreads(64, 1, 1)]
void Kernel2n64 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}

[numthreads(32, 1, 1)]
void Kernel2n32 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}

[numthreads(16, 1, 1)]
void Kernel2n16 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}

[numthreads(8, 1, 1)]
void Kernel2n8 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}

[numthreads(4, 1, 1)]
void Kernel2n4 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}

[numthreads(2, 1, 1)]
void Kernel2n2 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}

[numthreads(1, 1, 1)]
void Kernel2n1 (uint3 id : SV_DispatchThreadID) {
    Kernel2n(id);
}


void OctreeLeafsKernel (uint3 id) {

    for (uint i = 0; i < treeLeafsCount; i++) {
        TreeLeafs[uint2(i, id.x)] = half4(0, 0, 0, 0);
    }

    float3 pos = Position[id.x];

    float3 I = float3(0, 0, 0);
    float3 M = float3((pos.x - xmin) / (xmax - xmin), (pos.y - ymin) / (ymax - ymin), (pos.z - zmin) / (zmax - zmin));

    int N = 2;

    for (uint d = 0; d < treeDepth; d++) {
        float3 P = (I + frac(M * pow(N, d))) * 2;
        I.x = Octree[P].x;
    }

    TreeLeafs[uint2(I.x, id.x)] = half4(1, 0, 0, 0);
}

[numthreads(64, 1, 1)]
void OctreeLeafsKernel64 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}

[numthreads(32, 1, 1)]
void OctreeLeafsKernel32 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}

[numthreads(16, 1, 1)]
void OctreeLeafsKernel16 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}

[numthreads(8, 1, 1)]
void OctreeLeafsKernel8 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}

[numthreads(4, 1, 1)]
void OctreeLeafsKernel4 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}

[numthreads(2, 1, 1)]
void OctreeLeafsKernel2 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}

[numthreads(1, 1, 1)]
void OctreeLeafsKernel1 (uint3 id : SV_DispatchThreadID) {
    OctreeLeafsKernel(id);
}


void OctreeNeighborsKernel (uint3 id) {

    float3 pos = Position[id.x];
    float3 dir = Direction[id.x];
    float radii = PerceptionRadius[id.x];
    float hFOV = HorizontalFOV[id.x];
    float vFOV = VerticalFOV[id.x];

    float3 x = normalize(dir);
    float3 z = normalize(cross(x, float3(0, 1, 0)));
    float3 y = normalize(cross(z, x));
    
    float3 I = float3(0, 0, 0);
    float3 M = float3((pos.x - xmin) / (xmax - xmin), (pos.y - ymin) / (ymax - ymin), (pos.z - zmin) / (zmax - zmin));

    int N = 2;

    for (uint d = 0; d < treeDepth; d++) {
        float3 P = (I + frac(M * pow(N, d))) * 2;
        I.x = Octree[P].x;
    }

    for (uint i = 0; i < agentsCount; i++) {
        TreeNeighbors[uint2(id.x, i)] = half4(0, 0, 0, 0);
    }

    for (uint j = 0; j < agentsCount; j++) {
        TreeNeighbors[uint2(id.x, j)] = TreeLeafs[uint2(I.x, j)];
    }

    for (uint k = 0; k < neighborhoodCount; k++) {
        Neighborhood[id.x * neighborhoodCount + k] = -1;
    }

    uint ni = 0;
    uint ai = 0;

    while (ai < agentsCount && ni < neighborhoodCount) {
        if (TreeNeighbors[uint2(id.x, ai)].x > 0 && ai != id.x) {
            float3 npos = Position[ai];

            if (distance(pos, npos) <= radii) {

                float3 v = npos - pos;

                float3 p = float3(
                    x.x * v.x + x.y * v.y + x.z * v.z,
                    y.x * v.x + y.y * v.y + y.z * v.z,
                    z.x * v.x + z.y * v.y + z.z * v.z
                );

                float a_y = degrees(atan2(p.z, p.x));
                a_y *= -1;

                float a_z = degrees(atan2(p.y, p.x));

                if (abs(a_y) <= hFOV / 2 && abs(a_z) <= vFOV / 2) {
                    Neighborhood[id.x * neighborhoodCount + ni] = ai;
                    ni++;
                }
            }
        }
        ai++;
    }
}

[numthreads(64, 1, 1)]
void OctreeNeighborsKernel64 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}

[numthreads(32, 1, 1)]
void OctreeNeighborsKernel32 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}

[numthreads(16, 1, 1)]
void OctreeNeighborsKernel16 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}

[numthreads(8, 1, 1)]
void OctreeNeighborsKernel8 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}

[numthreads(4, 1, 1)]
void OctreeNeighborsKernel4 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}

[numthreads(2, 1, 1)]
void OctreeNeighborsKernel2 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}

[numthreads(1, 1, 1)]
void OctreeNeighborsKernel1 (uint3 id : SV_DispatchThreadID) {
    OctreeNeighborsKernel(id);
}
